name: Deploy to GitHub Pages

on:
  push:
    branches: [main] # main 브랜치에 코드가 푸시될 때마다 실행

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web --base-href "/Gachagame_todo/" # 💡 최신 플러터에서는 예쁜 CanvasKit이 강제 기본 적용되므로 에러를 뱉는 옵션 제거!

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
